<?php
namespace utility\constant;
/**
 * API Error constant
 **/
class ApiResponseConstant{
	
	//Authorization related error codes
	const CONTEXT_NOT_AUTHORIZED = 1001;
	const ROLE_NOT_AUTHORIZED = 1002;
	const UNAUTHORIZED_ACCESS = 1003;
	const ACCOUNT_LOCKED = 1004;
	const PASSWORD_EXPIRED = 1005; // Warning Code
	
	//Operation field releated error code
	const VALIDATION_FAILED = 1006;
	const CREATED_FAILED = 1007;
	const UPDATED_FAILED = 1009;
	const DELETED_FAILED = 1010;
	
	//common
	const INVALID_JSON_REQUEST = 1008;
	const MISSING_REQUIRED_PARAMETERS = 1052;
	const INVALID_VALUES_IN_PARAMETERS = 1053;
	const MAX_LENGTH_EXCEEDED = 1054;
	const UNKNOWN_ERROR_OCCURRED = 1055;
	const MODIFICATION_NOT_ALLOWED = 1852;
	const REPEATED_UNIQUE_KEYS = 1061;
	const PROV_NO_RESPONSE = 1057;
	const MIN_LENGTH_NOT_REACHED = 1058;
	const TRANSLATED_ERROR_MESSAGE = 1060;
	const FAILURE_ON_DOMAIN_RESOURCE_UPDATE = 1064;
	const BATCH_FILE_VERSION_NOT_EXISTS = 1065;
	const USER_DETAILS_REQUIRED = 1066;
	
	//data error status code
	const RESOURCE_IN_USE = 1021;
	const RESOURCE_ALREADY_EXIST = 1022;
	const RESOURCE_NOT_EXISTS = 1023;
	const UNABLE_TO_REMOVE_RESOURCE = 1024;
	const UNABLE_TO_SAVE_RESOURCE = 1025;
	const UNABLE_TO_UPDATE_RESOURCE = 1026;
	const UNABLE_TO_CONNECT_PROVISIONING_SYSTEM = 1027;
	
	//group Related 
	const UNABLE_TO_DELETE_GROUP_TENANT_EXIST = 1100;

	//access level related
	const UNABLE_TO_DELETE_ACCESS_LEVEL_USER_EXIST = 1200;
	
	//order related
	const PRODUCT_NON_PROVISIONABLE = 1300;
	const DISCOUNT_NON_PROVISIONABLE = 1301;
	const ORDER_EXPIRED = 1302;
	const ORDER_PRODUCT_VALIDATION = 1302;
	const ORDER_PRODUCT_CONFIRMED = 1303;
	const ORDER_PRODUCT_REJECTED = 1304;
	const ORDER_PRODUCT_RETURNED = 1305;

	//user related
	const AUTHENTICATION_FAILED = 1400;
	const USER_DELETED = 1401;
	const USER_INACTIVE = 1402;
	
	//discount related
	const UNABLE_TO_DELETE_DISCOUNT_PRODUCT_EXIST = 1500;
}